site_name: Eyes Unstrung 
site_url: https://joeldodson.github.io/eyesunstrung
repo_url: https://github.com/joeldodson/eyesunstrung
repo_name: eyesunstrung on GitHub
site_description: developing an accessible application to help blind and low vision people learn music
site_author: Joel Dodson

nav:
  - Home: index.md
  - About: about.md
  - Blog: 
    - List of Articles: blog/index.md 
    - Something New: blog/something_new.md

theme:
  name: material
  features:
    - content.code.copy                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

## 
# watch is to tell mkdocs serve extra directories or files to watch for changes 
#
watch:
  - src

